## Module 20 Group 1 Final: Data Cleaning

In [19]:
# import dependencies
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, func
import psycopg2
import numpy as np
from pathlib import Path

### Connect to cloud to read in data files

In [20]:
#format is //user:password@sql instance public IP address/database name
#db_string = f"postgres://postgres:alcohol-ca@35.194.17.20/alcohol_cloud"

In [21]:
#create engine
#engine = create_engine(db_string)

NameError: name 'db_string' is not defined

In [ ]:
#import one of the following tables 
# alcohol_ca (very big messy merged table)
# alcohol_ca_clean (coming soon after data cleanup)
# alcohol_qrt_mile (original raw dataset)
# personal_income
# typology_ca
# unemployment
#df = pd.read_sql_table('alcohol_ca',engine)
#df

### Read in csv files: cloud ip addrees not working

In [23]:
# Read in output CSV
#file_path = Path('alcohol_ca_clean.csv')
file_path = Path('alcohol_ca_clean_w_geonames.csv')
df = pd.read_csv(file_path)
df

,Unnamed: 0,county_name,geoname,geotype,region_name,num_people_qrt,tot_people,pct_of_total,per_capita_income,total_income,...,median_house_pct,metro_status,economic_type_label,low_education_2015,low_employment_cnty,pop_loss_2010,retirement_dest_2015,persistent_poverty_2013,persistent_child_poverty_2013,race_eth_updt
0,0,Alameda,4421,CT,no_region,0,0,0.00,56261,90631392,...,1.338,1,Nonspecialized,0,0,0,0,0,0,Other
1,1,Alameda,Alameda,CD,Bay Area,159,247,64.37,56261,90631392,...,1.338,1,Nonspecialized,0,0,0,0,0,0,Other
2,2,Alameda,Alameda,CD,Bay Area,2674,4516,59.21,56261,90631392,...,1.338,1,Nonspecialized,0,0,0,0,0,0,AfricanAm
3,3,Alameda,Alameda,CD,Bay Area,14243,22822,62.41,56261,90631392,...,1.338,1,Nonspecialized,0,0,0,0,0,0,Asian
4,4,Alameda,Alameda,CD,Bay Area,5689,8092,70.30,56261,90631392,...,1.338,1,Nonspecialized,0,0,0,0,0,0,Latino
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80275,90309,Yuba,Wheatland city,PL,Sacramento Area,315,620,50.81,34989,2587968,...,0.704,1,Federal/State Government,1,1,0,0,0,1,Latino
80276,90310,Yuba,Wheatland city,PL,Sacramento Area,71,153,46.41,34989,2587968,...,0.704,1,Federal/State Government,1,1,0,0,0,1,Multiple
80277,90311,Yuba,Wheatland city,PL,Sacramento Area,0,4,0.00,34989,2587968,...,0.704,1,Federal/State Government,1,1,0,0,0,1,Other
80278,90312,Yuba,Wheatland city,PL,Sacramento Area,0,7,0.00,34989,2587968,...,0.704,1,Federal/State Government,1,1,0,0,0,1,Other
80279,90314,Yuba,Wheatland city,PL,Sacramento Area,1118,2399,46.60,34989,2587968,...,0.704,1,Federal/State Government,1,1,0,0,0,1,White

In [24]:
# Read in original alcohol file to create separate df where Race = "Total" to get total population by ct/region, etc.
file_path = Path('population_pct_within_qrt_mile_alcohol.csv')
df_total = pd.read_csv(file_path)
df_total.head(50)

,Indicator_ID,ind_definition,reportyear,race_eth_code,race_eth_name,geotype,geotypevalue,geoname,county_name,county_fips_id,region_name,region_code,license_type,num_people_qrt,tot_people,pct_of_total
0,774,Percent of Population within 1/4 Mile of Alcoh...,2014,8,Other,CT,6001442100,4421,Alameda,6001,NaN,NaN,Total_licenses,0.0,0.0,NaN
1,774,Percent of Population within 1/4 Mile of Alcoh...,2014,1,AIAN,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,159.0,247.0,64.37
2,774,Percent of Population within 1/4 Mile of Alcoh...,2014,3,AfricanAm,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,2674.0,4516.0,59.21
3,774,Percent of Population within 1/4 Mile of Alcoh...,2014,2,Asian,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,14243.0,22822.0,62.41
4,774,Percent of Population within 1/4 Mile of Alcoh...,2014,4,Latino,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,5689.0,8092.0,70.30
5,774,Percent of Population within 1/4 Mile of Alcoh...,2014,7,Multiple,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,2490.0,4047.0,61.53
6,774,Percent of Population within 1/4 Mile of Alcoh...,2014,5,NHOPI,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,219.0,342.0,64.04
7,774,Percent of Population within 1/4 Mile of Alcoh...,2014,8,Other,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,164.0,278.0,58.99
8,774,Percent of Population within 1/4 Mile of Alcoh...,2014,9,Total,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,48112.0,73812.0,65.18
9,774,Percent of Population within 1/4 Mile of Alcoh...,2014,6,White,CD,600190020,Alameda,Alameda,6001,Bay Area,1.0,Total_licenses,22474.0,33468.0,67.15
10,774,Percent of Population within 1/4 Mile of Alcoh...,2014,1,AIAN,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,253.0,272.0,93.01
11,774,Percent of Population within 1/4 Mile of Alcoh...,2014,3,AfricanAm,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,10788.0,11517.0,93.67
12,774,Percent of Population within 1/4 Mile of Alcoh...,2014,2,Asian,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,24101.0,27253.0,88.43
13,774,Percent of Population within 1/4 Mile of Alcoh...,2014,4,Latino,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,12529.0,14100.0,88.86
14,774,Percent of Population within 1/4 Mile of Alcoh...,2014,7,Multiple,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,5559.0,6492.0,85.63
15,774,Percent of Population within 1/4 Mile of Alcoh...,2014,5,NHOPI,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,179.0,202.0,88.61
16,774,Percent of Population within 1/4 Mile of Alcoh...,2014,8,Other,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,514.0,608.0,84.54
17,774,Percent of Population within 1/4 Mile of Alcoh...,2014,9,Total,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,110403.0,131119.0,84.20
18,774,Percent of Population within 1/4 Mile of Alcoh...,2014,6,White,CD,600190200,Berkeley,Alameda,6001,Bay Area,1.0,Total_licenses,56480.0,70675.0,79.92
19,774,Percent of Population within 1/4 Mile of Alcoh...,2014,1,AIAN,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,295.0,669.0,44.10
20,774,Percent of Population within 1/4 Mile of Alcoh...,2014,3,AfricanAm,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,6205.0,12780.0,48.55
21,774,Percent of Population within 1/4 Mile of Alcoh...,2014,2,Asian,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,60002.0,153913.0,38.98
22,774,Percent of Population within 1/4 Mile of Alcoh...,2014,4,Latino,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,28964.0,62169.0,46.59
23,774,Percent of Population within 1/4 Mile of Alcoh...,2014,7,Multiple,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,5919.0,14258.0,41.51
24,774,Percent of Population within 1/4 Mile of Alcoh...,2014,5,NHOPI,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,1153.0,2494.0,46.23
25,774,Percent of Population within 1/4 Mile of Alcoh...,2014,8,Other,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,265.0,627.0,42.26
26,774,Percent of Population within 1/4 Mile of Alcoh...,2014,9,Total,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,132506.0,325166.0,40.75
27,774,Percent of Population within 1/4 Mile of Alcoh...,2014,6,White,CD,600191070,Fremont,Alameda,6001,Bay Area,1.0,Total_licenses,29703.0,78256.0,37.96
28,774,Percent of Population within 1/4 Mile of Alcoh...,2014,1,AIAN,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,707.0,1193.0,59.26
29,774,Percent of Population within 1/4 Mile of Alcoh...,2014,3,AfricanAm,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,26116.0,39877.0,65.49
30,774,Percent of Population within 1/4 Mile of Alcoh...,2014,2,Asian,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,40139.0,81387.0,49.32
31,774,Percent of Population within 1/4 Mile of Alcoh...,2014,4,Latino,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,75930.0,123646.0,61.41
32,774,Percent of Population within 1/4 Mile of Alcoh...,2014,7,Multiple,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,7101.0,13528.0,52.49
33,774,Percent of Population within 1/4 Mile of Alcoh...,2014,5,NHOPI,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,3353.0,6144.0,54.57
34,774,Percent of Population within 1/4 Mile of Alcoh...,2014,8,Other,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,466.0,859.0,54.25
35,774,Percent of Population within 1/4 Mile of Alcoh...,2014,9,Total,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,202909.0,366577.0,55.35
36,774,Percent of Population within 1/4 Mile of Alcoh...,2014,6,White,CD,600191260,Hayward,Alameda,6001,Bay Area,1.0,Total_licenses,49097.0,99943.0,49.13
37,774,Percent of Population within 1/4 Mile of Alcoh...,2014,1,AIAN,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,168.0,571.0,29.42
38,774,Percent of Population within 1/4 Mile of Alcoh...,2014,3,AfricanAm,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,1741.0,6930.0,25.12
39,774,Percent of Population within 1/4 Mile of Alcoh...,2014,2,Asian,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,11600.0,35342.0,32.82
40,774,Percent of Population within 1/4 Mile of Alcoh...,2014,4,Latino,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,13276.0,31457.0,42.20
41,774,Percent of Population within 1/4 Mile of Alcoh...,2014,7,Multiple,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,2424.0,7449.0,32.54
42,774,Percent of Population within 1/4 Mile of Alcoh...,2014,5,NHOPI,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,231.0,641.0,36.04
43,774,Percent of Population within 1/4 Mile of Alcoh...,2014,8,Other,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,203.0,507.0,40.04
44,774,Percent of Population within 1/4 Mile of Alcoh...,2014,9,Total,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,65616.0,202117.0,32.46
45,774,Percent of Population within 1/4 Mile of Alcoh...,2014,6,White,CD,600191660,Livermore-Pleasanton,Alameda,6001,Bay Area,1.0,Total_licenses,35973.0,119220.0,30.17
46,774,Percent of Population within 1/4 Mile of Alcoh...,2014,1,AIAN,CD,600192230,Oakland,Alameda,6001,Bay Area,1.0,Total_licenses,1104.0,1237.0,89.25
47,774,Percent of Population within 1/4 Mile of Alcoh...,2014,3,AfricanAm,CD,600192230,Oakland,Alameda,6001,Bay Area,1.0,Total_licenses,91909.0,108506.0,84.70
48,774,Percent of Population within 1/4 Mile of Alcoh...,2014,2,Asian,CD,600192230,Oakland,Alameda,6001,Bay Area,1.0,Total_licenses,60303.0,69807.0,86.39
49,774,Percent of Population within 1/4 Mile of Alcoh...,2014,4,Latino,CD,600192230,Oakland,Alameda,6001,Bay Area,1.0,Total_licenses,90204.0,100425.0,89.82

### Create race = "Total" dataframe to merge with full dataframe

In [25]:
df_total = df_total[df_total.race_eth_code == 9]
#df_total = df_total[df_total.geotype == 'CO']
df_total = df_total[['geotype', 'geoname', 'county_name', 'num_people_qrt', "tot_people"]]
df_total = df_total.rename(columns = {'num_people_qrt': 'tot_people_qrt', 'tot_people': 'tot_people_region'}, inplace = False)
df_total

,geotype,geoname,county_name,tot_people_qrt,tot_people_region
8,CD,Alameda,Alameda,48112.0,73812.0
17,CD,Berkeley,Alameda,110403.0,131119.0
26,CD,Fremont,Alameda,132506.0,325166.0
35,CD,Hayward,Alameda,202909.0,366577.0
44,CD,Livermore-Pleasanton,Alameda,65616.0,202117.0
...,...,...,...,...,...
90412,RE,San Joaquin Valley,NaN,1555205.0,3971659.0
90421,RE,San Luis Obispo,NaN,101121.0,269637.0
90430,RE,Santa Barbara,NaN,192676.0,423895.0
90439,RE,Shasta,NaN,40086.0,177223.0
90448,RE,Southern California,NaN,9744365.0,18051534.0

In [26]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10050 entries, 8 to 90448
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   geotype            10050 non-null  object
 1   geoname            10050 non-null  object
 2   county_name        10035 non-null  object
 3   tot_people_qrt     9501 non-null   float64
 4   tot_people_region  10044 non-null  float64
dtypes: float64(2), object(3)
memory usage: 471.1+ KB

In [27]:
## replace null values with 0
df_total['tot_people_qrt'] = df_total['tot_people_qrt'].replace(np.nan, 0)
df_total['county_name'] = df_total['county_name'].replace(np.nan, "no_region")
df_total['tot_people_region'] = df_total['tot_people_region'].replace(np.nan, 0)
df_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10050 entries, 8 to 90448
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   geotype            10050 non-null  object
 1   geoname            10050 non-null  object
 2   county_name        10050 non-null  object
 3   tot_people_qrt     10050 non-null  float64
 4   tot_people_region  10050 non-null  float64
dtypes: float64(2), object(3)
memory usage: 471.1+ KB

### Check SQL database (full dataframe) and delete unncessary columns.

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80280 entries, 0 to 80279
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     80280 non-null  int64
 1   county_name                    80280 non-null  object
 2   geoname                        80280 non-null  object
 3   geotype                        80280 non-null  object
 4   region_name                    80280 non-null  object
 5   num_people_qrt                 80280 non-null  int64
 6   tot_people                     80280 non-null  int64
 7   pct_of_total                   80280 non-null  float64
 8   per_capita_income              80280 non-null  int64
 9   total_income                   80280 non-null  int64
 10  population                     80280 non-null  int64
 11  unemp_2014                     80280 non-null  float64
 12  median_house_price             80280 non-null  int64
 13  median_house_pct               80280 non-null  float64
 14  metro_status                   80280 non-null  int64
 15  economic_type_label            80280 non-null  object
 16  low_education_2015             80280 non-null  int64
 17  low_employment_cnty            80280 non-null  int64
 18  pop_loss_2010                  80280 non-null  int64
 19  retirement_dest_2015           80280 non-null  int64
 20  persistent_poverty_2013        80280 non-null  int64
 21  persistent_child_poverty_2013  80280 non-null  int64
 22  race_eth_updt                  80280 non-null  object
dtypes: float64(3), int64(14), object(6)
memory usage: 14.1+ MB

In [29]:
df= df.drop(columns = 'Unnamed: 0', axis=1)
df

,county_name,geoname,geotype,region_name,num_people_qrt,tot_people,pct_of_total,per_capita_income,total_income,population,...,median_house_pct,metro_status,economic_type_label,low_education_2015,low_employment_cnty,pop_loss_2010,retirement_dest_2015,persistent_poverty_2013,persistent_child_poverty_2013,race_eth_updt
0,Alameda,4421,CT,no_region,0,0,0.00,56261,90631392,1610921,...,1.338,1,Nonspecialized,0,0,0,0,0,0,Other
1,Alameda,Alameda,CD,Bay Area,159,247,64.37,56261,90631392,1610921,...,1.338,1,Nonspecialized,0,0,0,0,0,0,Other
2,Alameda,Alameda,CD,Bay Area,2674,4516,59.21,56261,90631392,1610921,...,1.338,1,Nonspecialized,0,0,0,0,0,0,AfricanAm
3,Alameda,Alameda,CD,Bay Area,14243,22822,62.41,56261,90631392,1610921,...,1.338,1,Nonspecialized,0,0,0,0,0,0,Asian
4,Alameda,Alameda,CD,Bay Area,5689,8092,70.30,56261,90631392,1610921,...,1.338,1,Nonspecialized,0,0,0,0,0,0,Latino
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80275,Yuba,Wheatland city,PL,Sacramento Area,315,620,50.81,34989,2587968,73966,...,0.704,1,Federal/State Government,1,1,0,0,0,1,Latino
80276,Yuba,Wheatland city,PL,Sacramento Area,71,153,46.41,34989,2587968,73966,...,0.704,1,Federal/State Government,1,1,0,0,0,1,Multiple
80277,Yuba,Wheatland city,PL,Sacramento Area,0,4,0.00,34989,2587968,73966,...,0.704,1,Federal/State Government,1,1,0,0,0,1,Other
80278,Yuba,Wheatland city,PL,Sacramento Area,0,7,0.00,34989,2587968,73966,...,0.704,1,Federal/State Government,1,1,0,0,0,1,Other
80279,Yuba,Wheatland city,PL,Sacramento Area,1118,2399,46.60,34989,2587968,73966,...,0.704,1,Federal/State Government,1,1,0,0,0,1,White

### Sum the binned race/ethnic categories from full dataframe

In [30]:
# add geoname with new csv file
df_sum = df.groupby(['geotype', 'geoname', 'county_name','race_eth_updt'], 
                    as_index=False).agg({'num_people_qrt': 'sum', 
                                         'tot_people': 'sum',
                                         'region_name' : 'first',
                                         'per_capita_income' : 'first',
                                         'total_income' : 'first',
                                         'population' : 'first',
                                         'unemp_2014' : 'first',
                                         'median_house_price' : 'first',
                                         'median_house_pct' : 'first',
                                         'metro_status' : 'first',
                                         'economic_type_label' : 'first',
                                         'low_education_2015' : 'first',
                                         'low_employment_cnty' : 'first',
                                         'pop_loss_2010' : 'first',
                                         'retirement_dest_2015' : 'first',
                                         'persistent_poverty_2013' : 'first',
                                         'persistent_child_poverty_2013' : 'first'})
 
df_sum

,geotype,geoname,county_name,race_eth_updt,num_people_qrt,tot_people,region_name,per_capita_income,total_income,population,...,median_house_price,median_house_pct,metro_status,economic_type_label,low_education_2015,low_employment_cnty,pop_loss_2010,retirement_dest_2015,persistent_poverty_2013,persistent_child_poverty_2013
0,CD,Adin-Lookout,Modoc,AfricanAm,0,0,Northeast Sierra,40541,365803,9023,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
1,CD,Adin-Lookout,Modoc,Asian,0,0,Northeast Sierra,40541,365803,9023,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
2,CD,Adin-Lookout,Modoc,Latino,0,0,Northeast Sierra,40541,365803,9023,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
3,CD,Adin-Lookout,Modoc,Multiple,0,0,Northeast Sierra,40541,365803,9023,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
4,CD,Adin-Lookout,Modoc,Other,0,0,Northeast Sierra,40541,365803,9023,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60205,PL,Zayante CDP,Santa Cruz,Asian,0,4,Monterey Bay,52280,14209814,271804,...,85770,1.066,1,Recreation,0,0,0,0,0,0
60206,PL,Zayante CDP,Santa Cruz,Latino,6,57,Monterey Bay,52280,14209814,271804,...,85770,1.066,1,Recreation,0,0,0,0,0,0
60207,PL,Zayante CDP,Santa Cruz,Multiple,1,16,Monterey Bay,52280,14209814,271804,...,85770,1.066,1,Recreation,0,0,0,0,0,0
60208,PL,Zayante CDP,Santa Cruz,Other,1,4,Monterey Bay,52280,14209814,271804,...,85770,1.066,1,Recreation,0,0,0,0,0,0
60209,PL,Zayante CDP,Santa Cruz,White,80,614,Monterey Bay,52280,14209814,271804,...,85770,1.066,1,Recreation,0,0,0,0,0,0

### Merge new full dataframe (df_sum) with totals datframe (df_total) to calculate new percentages

In [31]:
##  need to update with geoname
df_new = pd.merge(df_sum, df_total, on=['geotype', 'geoname', 'county_name'], how="left")
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60210 entries, 0 to 60209
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   geotype                        60210 non-null  object
 1   geoname                        60210 non-null  object
 2   county_name                    60210 non-null  object
 3   race_eth_updt                  60210 non-null  object
 4   num_people_qrt                 60210 non-null  int64
 5   tot_people                     60210 non-null  int64
 6   region_name                    60210 non-null  object
 7   per_capita_income              60210 non-null  int64
 8   total_income                   60210 non-null  int64
 9   population                     60210 non-null  int64
 10  unemp_2014                     60210 non-null  float64
 11  median_house_price             60210 non-null  int64
 12  median_house_pct               60210 non-null  float64
 13  metro_status                   60210 non-null  int64
 14  economic_type_label            60210 non-null  object
 15  low_education_2015             60210 non-null  int64
 16  low_employment_cnty            60210 non-null  int64
 17  pop_loss_2010                  60210 non-null  int64
 18  retirement_dest_2015           60210 non-null  int64
 19  persistent_poverty_2013        60210 non-null  int64
 20  persistent_child_poverty_2013  60210 non-null  int64
 21  tot_people_qrt                 60210 non-null  float64
 22  tot_people_region              60210 non-null  float64
dtypes: float64(4), int64(13), object(6)
memory usage: 11.0+ MB

In [32]:
# re-order columns
df_new = df_new[['county_name',
                'geotype', 
                'geoname',
                'race_eth_updt',
                'num_people_qrt', 
                'tot_people', 
                'tot_people_qrt',
                'tot_people_region',
                'region_name',
                'per_capita_income',
                'total_income', 
                'population',
                'unemp_2014',
                'median_house_price',
                'median_house_pct',
                'metro_status',
                'economic_type_label',
                'low_education_2015', 
                'low_employment_cnty',  
                'pop_loss_2010',  
                'retirement_dest_2015', 
                'persistent_poverty_2013',
                'persistent_child_poverty_2013']]

#rename columns
df_new = df_new.rename(columns = {'num_people_qrt' : 'num_ppl_qrt_race',
                                  'tot_people' : 'tot_ppl_region_race'}, inplace = False)
df_new

,county_name,geotype,geoname,race_eth_updt,num_ppl_qrt_race,tot_ppl_region_race,tot_people_qrt,tot_people_region,region_name,per_capita_income,...,median_house_price,median_house_pct,metro_status,economic_type_label,low_education_2015,low_employment_cnty,pop_loss_2010,retirement_dest_2015,persistent_poverty_2013,persistent_child_poverty_2013
0,Modoc,CD,Adin-Lookout,AfricanAm,0,0,0.0,0.0,Northeast Sierra,40541,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
1,Modoc,CD,Adin-Lookout,Asian,0,0,0.0,0.0,Northeast Sierra,40541,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
2,Modoc,CD,Adin-Lookout,Latino,0,0,0.0,0.0,Northeast Sierra,40541,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
3,Modoc,CD,Adin-Lookout,Multiple,0,0,0.0,0.0,Northeast Sierra,40541,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
4,Modoc,CD,Adin-Lookout,Other,0,0,0.0,0.0,Northeast Sierra,40541,...,45311,0.563,0,Federal/State Government,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60205,Santa Cruz,PL,Zayante CDP,Asian,0,4,88.0,705.0,Monterey Bay,52280,...,85770,1.066,1,Recreation,0,0,0,0,0,0
60206,Santa Cruz,PL,Zayante CDP,Latino,6,57,88.0,705.0,Monterey Bay,52280,...,85770,1.066,1,Recreation,0,0,0,0,0,0
60207,Santa Cruz,PL,Zayante CDP,Multiple,1,16,88.0,705.0,Monterey Bay,52280,...,85770,1.066,1,Recreation,0,0,0,0,0,0
60208,Santa Cruz,PL,Zayante CDP,Other,1,4,88.0,705.0,Monterey Bay,52280,...,85770,1.066,1,Recreation,0,0,0,0,0,0
60209,Santa Cruz,PL,Zayante CDP,White,80,614,88.0,705.0,Monterey Bay,52280,...,85770,1.066,1,Recreation,0,0,0,0,0,0

### Calculate % of total race population and % of total pupolation for each race

In [35]:
# of the race/ethnic population living within a region, what percentage of the race/ethnicity lives within 0.25
df_new['pct_ppl_qrt_race'] = df_new['num_ppl_qrt_race'] / df_new['tot_ppl_region_race']

# of the total population living within a region within 0.25 miles, 
# what percentage is a given
df_new['pct_all_qrt_race'] = df_new['num_ppl_qrt_race'] / df_new['tot_people_qrt']

# of the total population living within a region, what percentage of a given race lives within 0.25 miles 
df_new['pct_all_ppl_qrt_race'] = df_new['tot_people_qrt'] / df_new['tot_people_region']


#df_state_pct['pct_total'] = df_state_pct['people_qtr_sum'] / df_state_pct['tot_people']
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60210 entries, 0 to 60209
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   county_name                    60210 non-null  object
 1   geotype                        60210 non-null  object
 2   geoname                        60210 non-null  object
 3   race_eth_updt                  60210 non-null  object
 4   num_ppl_qrt_race               60210 non-null  int64
 5   tot_ppl_region_race            60210 non-null  int64
 6   tot_people_qrt                 60210 non-null  float64
 7   tot_people_region              60210 non-null  float64
 8   region_name                    60210 non-null  object
 9   per_capita_income              60210 non-null  int64
 10  total_income                   60210 non-null  int64
 11  population                     60210 non-null  int64
 12  unemp_2014                     60210 non-null  float64
 13  median_house_price             60210 non-null  int64
 14  median_house_pct               60210 non-null  float64
 15  metro_status                   60210 non-null  int64
 16  economic_type_label            60210 non-null  object
 17  low_education_2015             60210 non-null  int64
 18  low_employment_cnty            60210 non-null  int64
 19  pop_loss_2010                  60210 non-null  int64
 20  retirement_dest_2015           60210 non-null  int64
 21  persistent_poverty_2013        60210 non-null  int64
 22  persistent_child_poverty_2013  60210 non-null  int64
 23  pct_ppl_qrt_race               59242 non-null  float64
 24  pct_all_qrt_race               56148 non-null  float64
 25  pct_all_ppl_qrt_race           59934 non-null  float64
dtypes: float64(7), int64(13), object(6)
memory usage: 12.4+ MB

In [36]:
# make a copy
df_final = df_new

# convert Nan percentages (where denominator = 0) to 0.
df_final['pct_ppl_qrt_race'] = df_final['pct_ppl_qrt_race'].replace(np.nan, 0)
df_final['pct_all_qrt_race'] = df_final['pct_all_qrt_race'].replace(np.nan, 0)
df_final['pct_all_ppl_qrt_race'] = df_final['pct_all_ppl_qrt_race'].replace(np.nan, 0)

df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60210 entries, 0 to 60209
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   county_name                    60210 non-null  object
 1   geotype                        60210 non-null  object
 2   geoname                        60210 non-null  object
 3   race_eth_updt                  60210 non-null  object
 4   num_ppl_qrt_race               60210 non-null  int64
 5   tot_ppl_region_race            60210 non-null  int64
 6   tot_people_qrt                 60210 non-null  float64
 7   tot_people_region              60210 non-null  float64
 8   region_name                    60210 non-null  object
 9   per_capita_income              60210 non-null  int64
 10  total_income                   60210 non-null  int64
 11  population                     60210 non-null  int64
 12  unemp_2014                     60210 non-null  float64
 13  median_house_price             60210 non-null  int64
 14  median_house_pct               60210 non-null  float64
 15  metro_status                   60210 non-null  int64
 16  economic_type_label            60210 non-null  object
 17  low_education_2015             60210 non-null  int64
 18  low_employment_cnty            60210 non-null  int64
 19  pop_loss_2010                  60210 non-null  int64
 20  retirement_dest_2015           60210 non-null  int64
 21  persistent_poverty_2013        60210 non-null  int64
 22  persistent_child_poverty_2013  60210 non-null  int64
 23  pct_ppl_qrt_race               60210 non-null  float64
 24  pct_all_qrt_race               60210 non-null  float64
 25  pct_all_ppl_qrt_race           60210 non-null  float64
dtypes: float64(7), int64(13), object(6)
memory usage: 12.4+ MB

### Test data and caluclations

In [37]:
# re-order columns
df_final = df_new[['county_name',
                'geotype', 
                'geoname',
                'race_eth_updt',
                'num_ppl_qrt_race', 
                'tot_ppl_region_race', 
                'tot_people_qrt',
                'tot_people_region', 
                'pct_ppl_qrt_race',
                'pct_all_qrt_race',
                'pct_all_ppl_qrt_race',  
                'region_name',
                'per_capita_income',
                'total_income', 
                'population',
                'unemp_2014',
                'median_house_price',
                'median_house_pct',
                'metro_status',
                'economic_type_label',
                'low_education_2015', 
                'low_employment_cnty',  
                'pop_loss_2010',  
                'retirement_dest_2015', 
                'persistent_poverty_2013',
                'persistent_child_poverty_2013']]

In [38]:
df_test = df_final[df_final.county_name == "Alameda"]
df_test = df_test[df_test.geotype == "PL"]
df_test.head(50)

,county_name,geotype,geoname,race_eth_updt,num_ppl_qrt_race,tot_ppl_region_race,tot_people_qrt,tot_people_region,pct_ppl_qrt_race,pct_all_qrt_race,...,median_house_price,median_house_pct,metro_status,economic_type_label,low_education_2015,low_employment_cnty,pop_loss_2010,retirement_dest_2015,persistent_poverty_2013,persistent_child_poverty_2013
51132,Alameda,PL,Alameda city,AfricanAm,2674,4516,48112.0,73812.0,0.592117,0.055579,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51133,Alameda,PL,Alameda city,Asian,14243,22822,48112.0,73812.0,0.624091,0.296038,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51134,Alameda,PL,Alameda city,Latino,5689,8092,48112.0,73812.0,0.703040,0.118245,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51135,Alameda,PL,Alameda city,Multiple,2490,4047,48112.0,73812.0,0.615271,0.051754,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51136,Alameda,PL,Alameda city,Other,542,867,48112.0,73812.0,0.625144,0.011265,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51137,Alameda,PL,Alameda city,White,22474,33468,48112.0,73812.0,0.671507,0.467118,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51144,Alameda,PL,Albany city,AfricanAm,545,621,15280.0,18539.0,0.877617,0.035668,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51145,Alameda,PL,Albany city,Asian,4883,5754,15280.0,18539.0,0.848627,0.319568,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51146,Alameda,PL,Albany city,Latino,1579,1891,15280.0,18539.0,0.835008,0.103338,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51147,Alameda,PL,Albany city,Multiple,794,956,15280.0,18539.0,0.830544,0.051963,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51148,Alameda,PL,Albany city,Other,148,181,15280.0,18539.0,0.817680,0.009686,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51149,Alameda,PL,Albany city,White,7331,9136,15280.0,18539.0,0.802430,0.479777,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51414,Alameda,PL,Ashland CDP,AfricanAm,3809,4085,18847.0,21925.0,0.932436,0.202101,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51415,Alameda,PL,Ashland CDP,Asian,3257,3967,18847.0,21925.0,0.821023,0.172813,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51416,Alameda,PL,Ashland CDP,Latino,8058,9394,18847.0,21925.0,0.857782,0.427548,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51417,Alameda,PL,Ashland CDP,Multiple,606,677,18847.0,21925.0,0.895126,0.032154,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51418,Alameda,PL,Ashland CDP,Other,343,389,18847.0,21925.0,0.881748,0.018199,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51419,Alameda,PL,Ashland CDP,White,2774,3413,18847.0,21925.0,0.812775,0.147185,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51696,Alameda,PL,Berkeley city,AfricanAm,10243,10896,95123.0,112580.0,0.940070,0.107682,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51697,Alameda,PL,Berkeley city,Asian,19218,21499,95123.0,112580.0,0.893902,0.202033,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51698,Alameda,PL,Berkeley city,Latino,10950,12209,95123.0,112580.0,0.896879,0.115114,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51699,Alameda,PL,Berkeley city,Multiple,4765,5536,95123.0,112580.0,0.860730,0.050093,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51700,Alameda,PL,Berkeley city,Other,798,901,95123.0,112580.0,0.885683,0.008389,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
51701,Alameda,PL,Berkeley city,White,49149,61539,95123.0,112580.0,0.798664,0.516689,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52446,Alameda,PL,Castro Valley CDP,AfricanAm,2187,4064,24317.0,61388.0,0.538140,0.089937,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52447,Alameda,PL,Castro Valley CDP,Asian,4191,12975,24317.0,61388.0,0.323006,0.172349,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52448,Alameda,PL,Castro Valley CDP,Latino,5283,10689,24317.0,61388.0,0.494246,0.217255,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52449,Alameda,PL,Castro Valley CDP,Multiple,977,2580,24317.0,61388.0,0.378682,0.040178,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52450,Alameda,PL,Castro Valley CDP,Other,323,682,24317.0,61388.0,0.473607,0.013283,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52451,Alameda,PL,Castro Valley CDP,White,11356,30398,24317.0,61388.0,0.373577,0.466998,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52560,Alameda,PL,Cherryland CDP,AfricanAm,1379,1585,13300.0,14728.0,0.870032,0.103684,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52561,Alameda,PL,Cherryland CDP,Asian,1228,1354,13300.0,14728.0,0.906942,0.092331,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52562,Alameda,PL,Cherryland CDP,Latino,7278,7955,13300.0,14728.0,0.914896,0.547218,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52563,Alameda,PL,Cherryland CDP,Multiple,351,401,13300.0,14728.0,0.875312,0.026391,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52564,Alameda,PL,Cherryland CDP,Other,341,362,13300.0,14728.0,0.941989,0.025639,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
52565,Alameda,PL,Cherryland CDP,White,2723,3071,13300.0,14728.0,0.886682,0.204737,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53376,Alameda,PL,Dublin city,AfricanAm,515,4214,13268.0,46036.0,0.122212,0.038815,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53377,Alameda,PL,Dublin city,Asian,3728,12170,13268.0,46036.0,0.306327,0.280977,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53378,Alameda,PL,Dublin city,Latino,1840,6663,13268.0,46036.0,0.276152,0.138680,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53379,Alameda,PL,Dublin city,Multiple,667,2027,13268.0,46036.0,0.329058,0.050271,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53380,Alameda,PL,Dublin city,Other,139,582,13268.0,46036.0,0.238832,0.010476,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53381,Alameda,PL,Dublin city,White,6379,20380,13268.0,46036.0,0.313003,0.480781,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53712,Alameda,PL,Emeryville city,AfricanAm,1733,1733,10080.0,10080.0,1.000000,0.171925,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53713,Alameda,PL,Emeryville city,Asian,2756,2756,10080.0,10080.0,1.000000,0.273413,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53714,Alameda,PL,Emeryville city,Latino,927,927,10080.0,10080.0,1.000000,0.091964,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53715,Alameda,PL,Emeryville city,Multiple,528,528,10080.0,10080.0,1.000000,0.052381,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53716,Alameda,PL,Emeryville city,Other,79,79,10080.0,10080.0,1.000000,0.007837,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53717,Alameda,PL,Emeryville city,White,4057,4057,10080.0,10080.0,1.000000,0.402480,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53802,Alameda,PL,Fairview CDP,AfricanAm,155,2047,850.0,10003.0,0.075721,0.182353,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0
53803,Alameda,PL,Fairview CDP,Asian,104,1484,850.0,10003.0,0.070081,0.122353,...,107589,1.338,1,Nonspecialized,0,0,0,0,0,0

In [39]:
df_final.to_csv('alcohol_ca_clean_final.csv')